name: Validate

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    name: Lint and Jest Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Use Node.js 14
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 14
          cache: yarn
      - run: yarn
      - run: yarn lint
      - run: yarn test
  cypress-run:
    name: Cypress Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Cypress Tests
        uses: cypress-io/github-action@v2
        with:
          build: yarn build
          start: yarn start
